spring: 
  application: 
    name: eureka-config-server
  cloud: 
    config: 
      server: 
        git: 
          uri: https://gitee.com/licerlee/springcloud-learning
          search-paths: /config-repos/src/main/resources/
          # 如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
server: 
  port: 7001
  
# 配置服务注册中心
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:1001/eureka/