spring:
  application:
    name: api-gateway-eureka

server:
  port: 1201

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
      
# 路由配置
  # 1.单路由配置
#zuul:
#  routes:
#  single-instance
#    api-a:
#      path: /api-a/**
#      url: http://localhost:2001/
#  multi-instance
#    api-b:
#      path: /api-b/**
#      serviceId: api-b
  
#api-b:
#  ribbon:
#    listOfServers: http://localhost:2001/, http://localhost:2002/